pipeline:
  publish:
    image: plugins/docker
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    repo: justinbarrick/announcebot
    tags:
    - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    when:
      event: push
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: kubernetes
    when:
      status: [success, failure]
